#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg PYTHON_VERSION="3.8.2" \
    --build-arg PYTHON_PIP_VERSION="20.1" \
    --build-arg PYTHON_XZ_GPG_KEY="E3FF2839C048B25C084DEBE9B26995E310250568" \
    --build-arg PIP_DOWNLOAD_HASH="1fe530e9e3d800be94e04f6428460fc4fb94f5a9" \
    --build-arg PYTHON_GET_PIP_SHA256="ce486cddac44e99496a702aa5c06c5028414ef48fdfd5242cd2fe559b13d4348" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
