#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build \
    --build-arg PYTHON_VERSION="3.9.2" \
    --build-arg PYTHON_PIP_VERSION="21.0.1" \
    --build-arg PYTHON_XZ_GPG_KEY="E3FF2839C048B25C084DEBE9B26995E310250568" \
    --build-arg PIP_DOWNLOAD_HASH="b60e2320d9e8d02348525bd74e871e466afdf77c" \
    --build-arg PYTHON_GET_PIP_SHA256="c3b81e5d06371e135fb3156dc7d8fd6270735088428c4a9a5ec1f342e2024565" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
