#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg PYTHON_VERSION="3.8.2" \
    --build-arg PYTHON_PIP_VERSION="20.0.2" \
    --build-arg PYTHON_XZ_GPG_KEY="E3FF2839C048B25C084DEBE9B26995E310250568" \
    --build-arg PIP_DOWNLOAD_HASH="d59197a3c169cef378a22428a3fa99d33e080a5d" \
    --build-arg PYTHON_GET_PIP_SHA256="421ac1d44c0cf9730a088e337867d974b91bdce4ea2636099275071878cc189e" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
