name: Docker image build push

on:
  pull_request:
    branches:
      - main
  push:
    branches:    
    - main

  workflow_dispatch:

jobs:
  docker_build:

    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage_tag: [
          { stage: 'default', tag: 'focal' },
          { stage: 'zsh', tag: 'focal-zsh' },
          { stage: 'zsh', tag: 'zsh' },
          { stage: 'default', tag: 'latest' }
        ]
    steps:
    - uses: actions/checkout@v3
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
    - name: Build ${{ matrix.stage_tag.tag }}
      env:
        DOCKER_BUILDKIT: 1
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
      run: docker build --rm --progress=plain --target="${{ matrix.stage_tag.stage }}" .
    - name: Hadolint
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
      uses: brpaz/hadolint-action@v1.5.0
      with:
        dockerfile: ./Dockerfile
  
  docker_push:
    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'

    strategy:
      matrix:
        stage_tag: [
          { stage: 'default', tag: 'focal' },
          { stage: 'zsh', tag: 'focal-zsh' },
          { stage: 'zsh', tag: 'zsh' },
          { stage: 'default', tag: 'latest' }
        ]
    steps:
    - uses: actions/checkout@v3
      if: github.event_name != 'pull_request'
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: poad
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build ${{ matrix.stage_tag.tag }} and push
      env:
        DOCKER_BUILDKIT: 1
      if: github.event_name != 'pull_request'
      run: |
        IMAGE_NAME=poad/docker-llvm-python:${{ matrix.stage_tag.tag }} && \
        ls -al && \
        docker build --rm --progress=plain --target="${{ matrix.stage_tag.stage }}" -t ${IMAGE_NAME} . && \
        docker push ${IMAGE_NAME}
