name: Docker image build push

on:
  pull_request:
    branches:
      - main
  push:
    branches:    
    - main

jobs:
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir_tag: [
          { dir: 'ubuntu', tag: 'focal' },
          { dir: 'ubuntu-zsh', tag: 'focal-zsh' },
          { dir: 'ubuntu-zsh', tag: 'zsh' },
          { dir: 'ubuntu', tag: 'latest' }
        ]
    steps:
    - uses: actions/checkout@master
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
    - name: Build ${{ matrix.dir_tag.tag }}
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
      run: |
        IMAGE_NAME=poad/docker-llvm-python:${{ matrix.dir_tag.tag }} && \
        DOCKERFILE_PATH=${{ matrix.dir_tag.dir }}/Dockerfile IMAGE_NAME=${IMAGE_NAME} hooks/build
    - name: Hadolint
      uses: brpaz/hadolint-action@master
      with:
        dockerfile: ${{ matrix.dir_tag.dir }}/Dockerfile
  
  docker_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir_tag: [
          { dir: 'ubuntu', tag: 'focal' },
          { dir: 'ubuntu-zsh', tag: 'focal-zsh' },
          { dir: 'ubuntu-zsh', tag: 'zsh' },
          { dir: 'ubuntu', tag: 'latest' }
        ]
    steps:
    - uses: actions/checkout@master
      if: github.event_name != 'pull_request'
    - name: Build ${{ matrix.dir_tag.tag }} and push
      if: github.event_name != 'pull_request'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u poad --password-stdin && \
        IMAGE_NAME=poad/docker-llvm-python:${{ matrix.dir_tag.tag }} && \
        DOCKERFILE_PATH=${{ matrix.dir_tag.dir }}/Dockerfile IMAGE_NAME=${IMAGE_NAME} hooks/build && \
        docker push ${IMAGE_NAME} && \
        cd ${CUR}
