name: Docker image build push

on:
  pull_request:
    branches:
      - master
  push:
    branches:    
    - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir_tag: [
          { dir: 'ubuntu', tag: 'focal' },
          { dir: 'ubuntu-zsh', tag: 'focal-zsh' },
          { dir: 'ubuntu-zsh', tag: 'zsh' },
          { dir: 'ubuntu', tag: 'latest' }
        ]
    steps:
    - uses: actions/checkout@master
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
    - name: Build ${{ matrix.dir_tag.tag }}
      if: github.event_name == 'pull_request' && github.event_name != 'schedule'
      run: DOCKERFILE_PATH=${{ matrix.dir_tag.dir }}/Dockerfile DOCKER_TAG=${{ matrix.dir_tag.tag }} IMAGE_NAME=poad/docker-llvm-python:${{ matrix.dir_tag.tag }} hooks/build

  docker_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir_tag: [
          { dir: 'ubuntu', tag: 'focal' },
          { dir: 'ubuntu-zsh', tag: 'focal-zsh' },
          { dir: 'ubuntu-zsh', tag: 'zsh' },
          { dir: 'ubuntu', tag: 'latest' }
        ]
    steps:
    - uses: actions/checkout@master
      if: github.event_name != 'pull_request' && github.event_name != 'schedule' && env.CHANGE_STATE != 'changed'
    - name: Build ${{ matrix.dir_tag.tag }} and push
      if: github.event_name != 'pull_request' && github.event_name != 'schedule' && env.CHANGE_STATE != 'changed'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u poad --password-stdin && \
        DOCKERFILE_PATH=${{ matrix.dir_tag.dir }}/Dockerfile DOCKER_TAG=${{ matrix.dir_tag.tag }} IMAGE_NAME=poad/docker-llvm-python:${{ matrix.dir_tag.tag }} hooks/build && \
        docker push $IMAGE_NAME && \
        cd ${CUR}
